services:
  backend:
    build: ./ygo_card_lib_server
    container_name: ygo_flask
    restart: always
    environment:
      DATABASE_HOST: db
      DATABASE_USER: user
      DATABASE_PASSWORD: password
      DATABASE_NAME: ygo_cards_db
    depends_on:
      - db

  frontend:
    build: ./ygo_card_lib_client
    container_name: ygo_vue
    ports:
      - "8080:80"   # expose frontend to external browsers
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: ygo_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ygo_cards_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
